# Generated by Django 3.1.1 on 2020-09-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='direccion',
        ),
    ]
